const restaurantList = [
    {
      id: "1",
      resName: "Meghna Foods",
      cuisin: "Biryani, North Indian, Asian",
      stars: "4.4",
      delTime: "32 minutes",
      costForTwo: 500,
      location: "Marathahalli, Bangalore",
      offers: "20% OFF on all orders",
      link: "https://ministryofcurry.com/wp-content/uploads/2024/06/chicken-biryani.jpg"
    },
    {
      id: "2",
      resName: "KFC",
      cuisin: "Burger, Fried Chicken",
      stars: "4.2",
      delTime: "30 minutes",
      costForTwo: 600,
      location: "MG Road, Delhi",
      offers: "Free fries on ₹400+",
      link: "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/RX_THUMBNAIL/IMAGES/VENDOR/2024/12/9/acb50783-bf74-4970-97c1-2d3bc1574435_594211.JPG",
    },
    {
      id: "3",
      resName: "Pizza Palace",
      cuisin: "Italian, Pizza",
      stars: "4.5",
      delTime: "28 minutes",
      costForTwo: 550,
      location: "Park Street, Kolkata",
      offers: "Buy 1 Get 1 Free",
      link: "https://b.zmtcdn.com/data/pictures/chains/3/18180053/1c622a6d33298b1b09dc541b6131dbd7_featured_v2.jpg?output-format=webp&fit=around|750:500&crop=750:500;*,*",
    },
    {
      id: "4",
      resName: "Sushi Zen",
      cuisin: "Japanese, Sushi",
      stars: "4.7",
      delTime: "45 minutes",
      costForTwo: 900,
      location: "Banjara Hills, Hyderabad",
      offers: "10% OFF with code SUSHI10",
      link: "https://www.shutterstock.com/shutterstock/photos/2208190/display_1500/stock-photo--rolls-of-sushi-in-a-zen-attitude-2208190.jpg",
    },
    {
      id: "5",
      resName: "Tandoori Flames",
      cuisin: "Tandoori, North Indian",
      stars: "4.3",
      delTime: "36 minutes",
      costForTwo: 700,
      location: "Sector 18, Noida",
      offers: "Flat ₹100 OFF on ₹599",
      link: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/d0/db/d1/tandoori-flame.jpg?w=1000&h=-1&s=1"
    },
    {
      id: "6",
      resName: "Wok & Roll",
      cuisin: "Chinese, Asian Fusion",
      stars: "4.6",
      delTime: "40 minutes",
      costForTwo: 650,
      location: "Hinjewadi, Pune",
      offers: "Free dessert on ₹499+",
      link: "https://m.media-amazon.com/images/I/71mqaKyNEML._SL1293_.jpg",
    },
  ];
  export default restaurantList;