const restaurantList = [
  {
    id: "1",
    resName: "Meghna Foods",
    cuisin: "Biryani, North Indian, Asian",
    stars: "4.4",
    delTime: "32 minutes",
    costForTwo: 500,
    location: "Marathahalli, Bangalore",
    offers: "20% OFF on all orders",
    link: "https://ministryofcurry.com/wp-content/uploads/2024/06/chicken-biryani.jpg"
  },
  {
    id: "2",
    resName: "KFC",
    cuisin: "Burger, Fried Chicken",
    stars: "4.2",
    delTime: "30 minutes",
    costForTwo: 600,
    location: "MG Road, Delhi",
    offers: "Free fries on ₹400+",
    link: "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/RX_THUMBNAIL/IMAGES/VENDOR/2024/12/9/acb50783-bf74-4970-97c1-2d3bc1574435_594211.JPG",
  },
  {
    id: "3",
    resName: "Pizza Palace",
    cuisin: "Italian, Pizza",
    stars: "4.5",
    delTime: "28 minutes",
    costForTwo: 550,
    location: "Park Street, Kolkata",
    offers: "Buy 1 Get 1 Free",
    link: "https://b.zmtcdn.com/data/pictures/chains/3/18180053/1c622a6d33298b1b09dc541b6131dbd7_featured_v2.jpg",
  },
  {
    id: "4",
    resName: "Sushi Zen",
    cuisin: "Japanese, Sushi",
    stars: "4.7",
    delTime: "45 minutes",
    costForTwo: 900,
    location: "Banjara Hills, Hyderabad",
    offers: "10% OFF with code SUSHI10",
    link: "https://www.shutterstock.com/shutterstock/photos/2208190/display_1500/stock-photo--rolls-of-sushi-in-a-zen-attitude-2208190.jpg",
  },
  {
    id: "5",
    resName: "Tandoori Flames",
    cuisin: "Tandoori, North Indian",
    stars: "4.3",
    delTime: "36 minutes",
    costForTwo: 700,
    location: "Sector 18, Noida",
    offers: "Flat ₹100 OFF on ₹599",
    link: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/d0/db/d1/tandoori-flame.jpg?w=1000&h=-1&s=1"
  },
  {
    id: "6",
    resName: "Wok & Roll",
    cuisin: "Chinese, Asian Fusion",
    stars: "4.6",
    delTime: "40 minutes",
    costForTwo: 650,
    location: "Hinjewadi, Pune",
    offers: "Free dessert on ₹499+",
    link: "https://m.media-amazon.com/images/I/71mqaKyNEML._SL1293_.jpg",
  },

  // 20 more restaurants
  {
    id: "7",
    resName: "Burger Hub",
    cuisin: "Burgers, Fast Food",
    stars: "4.3",
    delTime: "25 minutes",
    costForTwo: 400,
    location: "Brigade Road, Bangalore",
    offers: "Combo Meal ₹199",
    link: "https://images.unsplash.com/photo-1550547660-d9450f859349"
  },
  {
    id: "8",
    resName: "Spice Villa",
    cuisin: "Indian, Mughlai",
    stars: "4.5",
    delTime: "35 minutes",
    costForTwo: 750,
    location: "Connaught Place, Delhi",
    offers: "15% OFF for members",
    link: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f"
  },
  {
    id: "9",
    resName: "Green Leaf",
    cuisin: "Healthy, Salads",
    stars: "4.1",
    delTime: "22 minutes",
    costForTwo: 350,
    location: "Koregaon Park, Pune",
    offers: "Free smoothie on ₹300+",
    link: "https://images.unsplash.com/photo-1556761175-4b46a572b786"
  },
  {
    id: "10",
    resName: "Pasta Paradise",
    cuisin: "Italian, Pasta",
    stars: "4.4",
    delTime: "27 minutes",
    costForTwo: 500,
    location: "Salt Lake, Kolkata",
    offers: "Buy 2 Pastas, Get 1 Free",
    link: "https://images.unsplash.com/photo-1525755662778-989d0524087e"
  },
  {
    id: "11",
    resName: "The Steak House",
    cuisin: "Steak, Continental",
    stars: "4.6",
    delTime: "50 minutes",
    costForTwo: 1200,
    location: "Bandra, Mumbai",
    offers: "Free drink with steak",
    link: "https://images.unsplash.com/photo-1551183053-bf91a1d81141"
  },
  {
    id: "12",
    resName: "Wrap World",
    cuisin: "Wraps, Rolls",
    stars: "4.2",
    delTime: "20 minutes",
    costForTwo: 300,
    location: "Gariahat, Kolkata",
    offers: "Flat ₹50 OFF on ₹250",
    link: "https://images.unsplash.com/photo-1604908811704-0e5f94a6a4ae"
  },
  {
    id: "13",
    resName: "Seafood Shack",
    cuisin: "Seafood, Coastal",
    stars: "4.5",
    delTime: "42 minutes",
    costForTwo: 900,
    location: "Fort Kochi, Kerala",
    offers: "10% OFF on all seafood",
    link: "https://images.unsplash.com/photo-1604908177225-6c684b3a38be"
  },
  {
    id: "14",
    resName: "Bakers Delight",
    cuisin: "Bakery, Desserts",
    stars: "4.6",
    delTime: "18 minutes",
    costForTwo: 250,
    location: "Anna Nagar, Chennai",
    offers: "Free cupcake with cake",
    link: "https://images.unsplash.com/photo-1601979031896-27b4383fbb31"
  },
  {
    id: "15",
    resName: "Curry Corner",
    cuisin: "Indian, Curry",
    stars: "4.3",
    delTime: "33 minutes",
    costForTwo: 550,
    location: "Indiranagar, Bangalore",
    offers: "20% OFF curries",
    link: "https://images.unsplash.com/photo-1600628422010-8e4b1b8e8b49"
  },
  {
    id: "16",
    resName: "BBQ Nation",
    cuisin: "Barbecue, Buffet",
    stars: "4.5",
    delTime: "55 minutes",
    costForTwo: 1400,
    location: "Powai, Mumbai",
    offers: "Free dessert buffet",
    link: "https://images.unsplash.com/photo-1504674900247-0877df9cc836"
  },
  {
    id: "17",
    resName: "Veggie Delight",
    cuisin: "Vegetarian, Healthy",
    stars: "4.2",
    delTime: "25 minutes",
    costForTwo: 400,
    location: "Bapu Nagar, Jaipur",
    offers: "Free soup with main",
    link: "https://images.unsplash.com/photo-1528697203043-733dafdaa316"
  },
  {
    id: "18",
    resName: "Dimsum House",
    cuisin: "Chinese, Dim Sum",
    stars: "4.4",
    delTime: "30 minutes",
    costForTwo: 600,
    location: "South Extension, Delhi",
    offers: "Buy 2, Get 1 Free",
    link: "https://images.unsplash.com/photo-1626086179975-86d3a0139d88"
  },
  {
    id: "19",
    resName: "Ramen Republic",
    cuisin: "Japanese, Ramen",
    stars: "4.7",
    delTime: "35 minutes",
    costForTwo: 800,
    location: "Viman Nagar, Pune",
    offers: "15% OFF ramen bowls",
    link: "https://images.unsplash.com/photo-1621996346565-2f46b6b4a2f3"
  },
  {
    id: "20",
    resName: "Falafel Factory",
    cuisin: "Middle Eastern, Wraps",
    stars: "4.3",
    delTime: "20 minutes",
    costForTwo: 450,
    location: "Koramangala, Bangalore",
    offers: "Free drink with falafel wrap",
    link: "https://images.unsplash.com/photo-1617196038435-5f4c1f4e1e3c"
  },
  {
    id: "21",
    resName: "Grill Master",
    cuisin: "Grilled, Continental",
    stars: "4.5",
    delTime: "40 minutes",
    costForTwo: 950,
    location: "Civil Lines, Delhi",
    offers: "Free starter with main course",
    link: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85"
  },
  {
    id: "22",
    resName: "Taco Town",
    cuisin: "Mexican, Tacos",
    stars: "4.4",
    delTime: "28 minutes",
    costForTwo: 500,
    location: "Banjara Hills, Hyderabad",
    offers: "Buy 3 tacos, get 1 free",
    link: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092"
  },
  {
    id: "23",
    resName: "Ice Cream Bliss",
    cuisin: "Desserts, Ice Cream",
    stars: "4.8",
    delTime: "15 minutes",
    costForTwo: 300,
    location: "Sector 62, Noida",
    offers: "50% OFF second scoop",
    link: "https://images.unsplash.com/photo-1551024709-8f23befc6f87"
  },
  {
    id: "24",
    resName: "Hot Pot Heaven",
    cuisin: "Asian, Hot Pot",
    stars: "4.6",
    delTime: "50 minutes",
    costForTwo: 1200,
    location: "Whitefield, Bangalore",
    offers: "Free appetizer platter",
    link: "https://images.unsplash.com/photo-1605478522013-8d8a2a96ff63"
  },
  {
    id: "25",
    resName: "Pancake Point",
    cuisin: "Breakfast, Pancakes",
    stars: "4.5",
    delTime: "18 minutes",
    costForTwo: 350,
    location: "Park Circus, Kolkata",
    offers: "Free coffee with pancakes",
    link: "https://images.unsplash.com/photo-1550317138-10000687a72b"
  },
  {
    id: "26",
    resName: "Gourmet Bites",
    cuisin: "Continental, Fusion",
    stars: "4.4",
    delTime: "38 minutes",
    costForTwo: 800,
    location: "Andheri, Mumbai",
    offers: "10% OFF for first-time orders",
    link: "https://images.unsplash.com/photo-1504674900247-0877df9cc836"
  }
];

export default restaurantList;
